services:

    agit.page:
        class: Agit\PageBundle\Service\PageService
        arguments: [ @agit.pluggable.cache.loader_factory, @agit.common.url, @agit.intl.locale, @?agit.user ]
        tags: [{ name: agit.pluggable, type: cache, tag: agit.pages, baseClass: Agit\PageBundle\Plugin\PagePlugin }]

    # Handles our custom Twig syntax for the page meta data
    agit.page.custom:
        class: Agit\PageBundle\TwigMeta\PageConfigTokenExtension
        tags:
            - { name: twig.extension }

    # misc template functions
    agit.page.pagecontent:
        class: Agit\PageBundle\Twig\PageContentExtension
        tags:
            - { name: twig.extension }
        arguments:  [ @agit.page, @agit.intl.locale, @?agit.localedata.language ]

    # page navigation functions
    agit.page.pagenavigation:
        class: Agit\PageBundle\Twig\PageNavigationExtension
        tags:
            - { name: twig.extension }
        arguments:  [@agit.page]
